version: 0.0


env:
  parameter-store:
    LAMBDA_FUNCTION_NAME: /cfreeman_lab_4_5_3_function_name


Resources:
  - myLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: ${LAMBDA_FUNCTION_NAME}
        Alias: production
        CurrentVersion: {{ CURRENT_VERSION }}
        TargetVersion: {{ TARGET_VERSION }}