version: 0.0
Resources:
  - myLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: ${LAMBDA_FUNCTION_NAME}
        Alias: production
        CurrentVersion: {{ CURRENT_VERSION }}
        TargetVersion: {{ TARGET_VERSION }}