version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - npm install

  pre_build:
    commands:
      - echo "Installing dependencies..."
      - npm install
      - echo "Running tests..."
      - npm test || true

  build:
    commands:
      - echo "Building React application..."
      - npm run build
      - echo "Preparing Lambda deployment package..."
      - mkdir -p dist-lambda
      - cp -r static dist-lambda/
      - cp server.ts dist-lambda/
      - cp package.json dist-lambda/
      - cd dist-lambda
      - npm install --production
      - zip -r ../function.zip ./*
      - ls * ../function.zip ../appspec.yml

  post_build:
    commands:
      - echo "Updating Lambda function..."
      - aws lambda update-function-code --function-name ${LAMBDA_FUNCTION_NAME} --zip-file file://function.zip
      - ls function.zip
      - echo "Build completed on `date`"

artifacts:
  files:
    - function.zip
    - appspec.yml
  discard-paths: yes

cache:
  paths:
    - 'node_modules/**/*'