version: 0.2

env:
  parameter-store:
    LAMBDA_FUNCTION_NAME: /cfreeman_lab_4_5_3_function_name

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - npm install

  pre_build:
    commands:
      - echo "Installing dependencies..."
      - npm ci
      - npm test

  build:
    commands:
      - echo "Building React application..."
      - npm run build
      - echo "Preparing Lambda deployment package..."
      - mkdir -p dist-lambda
      - cp -r static dist-lambda/
      - echo "export { handler } from './server.js';" > dist-lambda/index.js
      - cp server.js dist-lambda/
      - cp package.json dist-lambda/
      - cp package-lock.json dist-lambda/
      - cd dist-lambda
      - echo "================== Listing dist-lambda =================="
      - ls
      - echo "================== End of dist-lambda listing =================="
      - npm ci --production
      - rm ./package-lock.json
      - zip -r ../function.zip ./*

  post_build:
    commands:
      - echo "Updating Lambda function..."
      - aws lambda update-function-code --function-name ${LAMBDA_FUNCTION_NAME} --zip-file fileb://../function.zip
      - echo "Build completed on `date`"

artifacts:
  files:
    - function.zip
    - appspec.yml
  discard-paths: yes

cache:
  paths:
    - 'node_modules/**/*'